version: '3.7'
services:
  kalilinux:
    hostname: kalilinux.lab
    build:
      context: ./
      dockerfile: Dockerfile
    image: 'csalab/kalilinux-docker:${VERSION:-latest}' # Other versions other than "latest" are slim and burpsuite
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - 0.0.0.0:8080:8080
    environment:
      - SHELL=/bin/bash
      - PASSWORD=${PASSWORD:-kalilinux} # Change kalilunux to your own custom password for the sign in page on the vnc server
    volumes:
      - data:/home/kali/Desktop
    entrypoint: ["/bin/bash", "/startup.sh"]

volumes:
  data: {}
